import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import SubscribeSection from "../../components/SubscribeSection";
import BlogSection from "../../components/BlogSection";
import HeroSection from "../../components/HeroSection";

const Blog = () => {
    const navigate = useNavigate();

    const blogs = [
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },

    ];

    // Show only 4 blogs initially
    const [visibleBlogs, setVisibleBlogs] = useState(8);

    // Load more blogs when clicking the button
    const handleLoadMore = () => {
        setVisibleBlogs(blogs.length); // Show all blogs
    };

    let index;

    return (
        <div className="">
            {/* Hero Section */}
            <HeroSection image="/blogheroimage.png" title="Blog" text="Welcome to the WiSchool Blog! Explore our collection of articles, insights, and resources on education, student success, parenting tips, and more. Whether you're a student, parent, educator, or member of the community, you'll find valuable information and inspiration to support your journey in education." />

            {/* Blog List */}
            <BlogSection show />

            {/* Load More Blogs */}
            {visibleBlogs < blogs.length && (
                <div className="flex justify-center p-4 pb-6 bg-[#E8ECE9]">
                    <button
                        onClick={handleLoadMore}
                        className="bg-[#FFFFFF] text-[#09B451] px-6 py-3 rounded  transition"
                    >
                        See More Updates
                    </button>
                </div>
            )}
        </div>
    );
};

export default Blog;
