export const studentSeedData = [
  {
    id: 1,
    studentId: "STU001",
    admissionNumber: "ADM001",
    firstName: "Amina",
    middleName: "",
    lastName: "Bello",
    name: "Amina Bello",
    className: "JSS 1",
    gender: "Female",
    dateOfBirth: "2012-05-10",
    email: "amina.bello@example.com",
    phone: "08012345678",
    address: "Kano, Nigeria",
    parentFullName: "Musa Bello",
    parentPhone: "08111111111",
    parentEmail: "musa.bello@example.com",
  },
  {
    id: 2,
    studentId: "STU002",
    admissionNumber: "ADM002",
    firstName: "Yusuf",
    middleName: "",
    lastName: "Danladi",
    name: "Yusuf Danladi",
    className: "JSS 2",
    gender: "Male",
    dateOfBirth: "2011-11-03",
    email: "yusuf.danladi@example.com",
    phone: "08023456789",
    address: "Kaduna, Nigeria",
    parentFullName: "Aisha Danladi",
    parentPhone: "08222222222",
    parentEmail: "aisha.danladi@example.com",
  },
];
