export const parentSeedData = [
  {
    id: 1,
    parentId: "WISCH47",
    name: "Danlami Yakubu",
    title: "Mr",
    firstName: "Danlami",
    lastName: "Yakubu",
    gender: "Male",
    mobile: "09132328374",
    email: "danjumadanlami@gmail.com",
    students: 1,
    state: "Kano",
    lga: "Kano Municipal",
    address: "Nassarawa GRA, Kano",
    image: "/api/placeholder/80/80",
  },
  {
    id: 2,
    parentId: "WISCH48",
    name: "Kashi Modu",
    title: "Mrs",
    firstName: "Kashi",
    lastName: "Modu",
    gender: "Female",
    mobile: "07083245673",
    email: "kolokoshavbuj@gmail.com",
    students: 2,
    state: "Kano",
    lga: "Fagge",
    address: "Fagge, Kano",
    image: "/api/placeholder/80/80",
  },
  {
    id: 3,
    parentId: "WISCH49",
    name: "Gogo Yawa",
    title: "Mrs",
    firstName: "Gogo",
    lastName: "Yawa",
    gender: "Female",
    mobile: "08123456789",
    email: "gogoyawa@gmail.com",
    students: 1,
    state: "Kano",
    lga: "Gwale",
    address: "Gwale, Kano",
    image: "/api/placeholder/80/80",
  },
  {
    id: 4,
    parentId: "WISCH50",
    name: "Sani Gana",
    title: "Mr",
    firstName: "Sani",
    lastName: "Gana",
    gender: "Male",
    mobile: "07098765432",
    email: "sanigana@gmail.com",
    students: 3,
    state: "Kano",
    lga: "Nasarawa",
    address: "Nasarawa, Kano",
    image: "/api/placeholder/80/80",
  },
  {
    id: 5,
    parentId: "WISCH51",
    name: "Steaven John",
    title: "Mr",
    firstName: "Steaven",
    lastName: "John",
    gender: "Male",
    mobile: "08087654321",
    email: "steavenjohn@gmail.com",
    students: 2,
    state: "Kano",
    lga: "Tarauni",
    address: "Tarauni, Kano",
    image: "/api/placeholder/80/80",
  },
  {
    id: 6,
    parentId: "WISCH52",
    name: "Lami Dangana",
    title: "Mrs",
    firstName: "Lami",
    lastName: "Dangana",
    gender: "Female",
    mobile: "09076543210",
    email: "lamidangana@gmail.com",
    students: 1,
    state: "Kano",
    lga: "Ungogo",
    address: "Ungogo, Kano",
    image: "/api/placeholder/80/80",
  },
  {
    id: 7,
    parentId: "WISCH53",
    name: "Hajara Madu",
    title: "Mrs",
    firstName: "Hajara",
    lastName: "Madu",
    gender: "Female",
    mobile: "08165432109",
    email: "hajaramadu@gmail.com",
    students: 4,
    state: "Kano",
    lga: "Kumbotso",
    address: "Kumbotso, Kano",
    image: "/api/placeholder/80/80",
  },
  {
    id: 8,
    parentId: "WISCH54",
    name: "Agnes Dako",
    title: "Mrs",
    firstName: "Agnes",
    lastName: "Dako",
    gender: "Female",
    mobile: "07054321098",
    email: "agnesdako@gmail.com",
    students: 2,
    state: "Kano",
    lga: "Kiru",
    address: "Kiru, Kano",
    image: "/api/placeholder/80/80",
  },
  {
    id: 9,
    parentId: "WISCH55",
    name: "Gogo Yunti",
    title: "Mr",
    firstName: "Gogo",
    lastName: "Yunti",
    gender: "Male",
    mobile: "08143210987",
    email: "gogoyunti@gmail.com",
    students: 1,
    state: "Kano",
    lga: "Rano",
    address: "Rano, Kano",
    image: "/api/placeholder/80/80",
  },
  {
    id: 10,
    parentId: "WISCH56",
    name: "Danlomi Yakolo",
    title: "Mr",
    firstName: "Danlomi",
    lastName: "Yakolo",
    gender: "Male",
    mobile: "09032109876",
    email: "danlomiyakolo@gmail.com",
    students: 3,
    state: "Kano",
    lga: "Dala",
    address: "Dala, Kano",
    image: "/api/placeholder/80/80",
  },
];
