export const eventSeedData = [
  {
    id: 1,
    title: "School Assembly",
    date: "2026-03-10",
    time: "08:00",
    location: "Auditorium",
    description: "Weekly school assembly for students and staff",
    organizer: "School Admin",
  },
  {
    id: 2,
    title: "Mathematics Competition",
    date: "2026-03-14",
    time: "10:00",
    location: "Lecture Hall A",
    description: "Inter-school mathematics challenge",
    organizer: "Math Department",
  },
  {
    id: 3,
    title: "Parent-Teacher Meeting",
    date: "2026-03-20",
    time: "11:00",
    location: "Conference Room",
    description: "Quarterly meeting with parents",
    organizer: "School Admin",
  },
  {
    id: 4,
    title: "Science Fair",
    date: "2026-03-22",
    time: "12:00",
    location: "Science Block",
    description: "Students display science projects",
    organizer: "Science Department",
  },
  {
    id: 5,
    title: "Career Day",
    date: "2026-03-27",
    time: "09:00",
    location: "Main Auditorium",
    description: "Professional talks and mentoring sessions",
    organizer: "Career Office",
  },
];
