import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom';
import SubscribeSection from './SubscribeSection';
import './blogSection.css'



const BlogSection = ({ show }) => {

    const navigate = useNavigate();

    const blogs = [
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },
        {
            id: 1, title: "Unlocking the Power of STEM Education:", sub: "Fostering Creativity and Innovation in the Classroom", author: "Ndaloke", date: "Fri, Mar 8, 2024, 7:00 AM ", description: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century.", content: "In today's rapidly evolving world, STEM education plays a crucial role in preparing students for success in the 21st century. By integrating science, technology, engineering, and mathematics into the curriculum, educators can inspire curiosity, foster critical thinking, and ignite a passion for discovery among their students.At WiSchool, we recognize the importance of STEM education in equipping students with the skills and knowledge they need to thrive in an increasingly complex and interconnected world.Our commitment to STEM is reflected in our innovative programs, hands- on learning experiences, and dedicated faculty who inspire students to explore, experiment, and excel in STEM subjects.Through project - based learning, collaborative problem - solving, and real - world applications, students at WiSchool engage in meaningful STEM experiences that go beyond the textbook and classroom.Whether it's designing and building robots, conducting experiments in our state-of-the-art science labs, or coding and programming in our technology classes, students are encouraged to think critically, communicate effectively, and persevere in the face of challenges.But STEM education is about more than just preparing students for future careers in science and technology.It's about nurturing creativity, fostering innovation, and empowering students to become lifelong learners and responsible global citizens. By embracing STEM education, we can inspire the next generation of innovators, inventors, and problem-solvers who will shape the future of our world.Join us on this exciting journey as we unlock the power of STEM education and empower students to reach new heights of discovery and achievement.", image: "/blogImage.png"
        },

    ];

    // Show only 4 blogs initially
    const [visibleBlogs, setVisibleBlogs] = useState(8);

    // Load more blogs when clicking the button
    const handleLoadMore = () => {
        setVisibleBlogs(blogs.length); // Show all blogs
    };

    let index;

    return (
        <section className="m-auto flex my-10 flex-col gap-6">
            {blogs.slice(0, visibleBlogs).map((blog, index) => (

                <React.Fragment key={blog.id}>
                    <div
                        className="bg-white blogsection w-[90%] mx-auto flex gap-6 h-[300px] items- justify-center shadow-md cursor-pointer hover:shadow-lg transition"
                        onClick={() => navigate(`/blog/${blog.id}`, { state: blog })}
                    >
                        <div className="w-[55%] imageSection h-full">
                            <img src={blog.image} alt={blog.title} className="h-full  w-full object-cover" />
                        </div>
                        <div className="p-1 pt-10">
                            <h3 className="text-[#2B2D32] text-[28px] font-bold">{blog.title}</h3>
                            <p className="mt-8 text-[15px] w-[86%] text-[#56585C]">{blog.description}</p>
                            <p className="text-[#989E99] mt-6 text-sm">By <span className="font-bold">{blog.author}</span>  {blog.date}</p>
                        </div>
                    </div>


                    {index === 3 && visibleBlogs > 4 && (
                        <div className={`${show ? '' : 'hidden'}`}>
                            <SubscribeSection show={true} />
                        </div>

                    )}
                </React.Fragment>
            ))}
        </section>
    )
}

export default BlogSection